import { randomUUID } from "node:crypto";
import { Resend } from "resend";
import { SITE } from "./site";

export type ContactPayload = {
  name: string;
  email: string;
  phone: string;
  details?: string;
  message: string;
};

export type EmailMode = "resend" | "log_only" | "fallback_sender";

export function getEmailMode(): EmailMode {
  const raw = (process.env.CONTACT_EMAIL_MODE || "resend").toLowerCase();
  if (raw === "log_only" || raw === "fallback_sender") return raw;
  return "resend";
}

function getSenderConfig(mode: EmailMode) {
  if (mode === "fallback_sender") {
    return {
      apiKey: process.env.RESEND_API_KEY_FALLBACK,
      from:
        process.env.CONTACT_EMAIL_FROM_FALLBACK ||
        "Destin Bonfire Company <bookings@30aflame.com>",
    };
  }
  return {
    apiKey: process.env.RESEND_API_KEY,
    from:
      process.env.CONTACT_EMAIL_FROM ||
      "Destin Bonfire Company <bookings@destinbonfirecompany.com>",
  };
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// CAN-SPAM compliance footer — every email this site ever sends gets these
// blocks: a physical postal address, a clear identification of who sent it
// and why, and a working unsubscribe path. Required for marketing email and
// good practice for transactional/notification email per Resend's
// deliverability guide.
function htmlFooter({ unsubscribeUrl }: { unsubscribeUrl: string }) {
  const addr = SITE.address;
  return `<table cellspacing="0" cellpadding="0" style="margin-top:28px;width:100%;border-collapse:collapse;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;">
<tr><td style="padding:16px 0;border-top:1px solid #e5dcd0;color:#777;font-size:12px;line-height:1.55;">
<p style="margin:0 0 8px 0;color:#555;"><strong>${escapeHtml(SITE.name)}</strong></p>
<p style="margin:0 0 6px 0;">
${escapeHtml(addr.street)}, ${escapeHtml(addr.city)}, ${escapeHtml(addr.region)} ${escapeHtml(addr.postal)}, ${escapeHtml(addr.country)}<br>
<a href="${escapeHtml(SITE.phoneHref)}" style="color:#777;text-decoration:none;">${escapeHtml(SITE.phone)}</a> &nbsp;·&nbsp;
<a href="${escapeHtml(SITE.emailHref)}" style="color:#777;text-decoration:none;">${escapeHtml(SITE.email)}</a>
</p>
<p style="margin:8px 0 0 0;">You are receiving this email because it was generated by an action on <a href="${escapeHtml(SITE.domain)}" style="color:#777;">${escapeHtml(SITE.domain.replace(/^https?:\/\//, ""))}</a>. <a href="${escapeHtml(unsubscribeUrl)}" style="color:#777;">Unsubscribe</a>.</p>
</td></tr>
</table>`;
}

function textFooter({ unsubscribeUrl }: { unsubscribeUrl: string }) {
  const addr = SITE.address;
  return [
    "",
    "—",
    SITE.name,
    `${addr.street}, ${addr.city}, ${addr.region} ${addr.postal}, ${addr.country}`,
    `${SITE.phone} · ${SITE.email}`,
    "",
    `You are receiving this email because it was generated by an action on ${SITE.domain.replace(/^https?:\/\//, "")}.`,
    `Unsubscribe: ${unsubscribeUrl}`,
  ].join("\n");
}

function buildHtmlBody(p: ContactPayload, footer: string): string {
  const rows: [string, string][] = [
    ["Name", p.name],
    ["Email", p.email],
    ["Phone", p.phone],
    ["Group size & date", p.details || "—"],
    ["Message", p.message],
  ];
  const rowsHtml = rows
    .map(
      ([label, value]) =>
        `<tr><td style="padding:8px 12px;background:#f7f3ec;font-weight:600;color:#1b1b1b;width:180px;vertical-align:top;">${escapeHtml(
          label,
        )}</td><td style="padding:8px 12px;color:#222;vertical-align:top;white-space:pre-wrap;">${escapeHtml(
          value,
        )}</td></tr>`,
    )
    .join("");
  return `<!doctype html><html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;background:#fff;color:#1b1b1b;margin:0;padding:24px;">
<div style="max-width:640px;margin:0 auto;">
<h2 style="margin:0 0 16px 0;color:#c25a2e;">New booking inquiry</h2>
<p style="margin:0 0 20px 0;color:#555;font-size:14px;">From the contact form at ${escapeHtml(SITE.domain.replace(/^https?:\/\//, ""))}.</p>
<table cellspacing="0" cellpadding="0" style="border:1px solid #e5dcd0;border-radius:8px;overflow:hidden;width:100%;border-collapse:collapse;font-size:14px;">
${rowsHtml}
</table>
<p style="margin:20px 0 0 0;color:#888;font-size:12px;">Reply directly to this email to respond to ${escapeHtml(
    p.name,
  )}.</p>
${footer}
</div>
</body></html>`;
}

function buildTextBody(p: ContactPayload, footer: string): string {
  return [
    "New booking inquiry from the Destin Bonfire Company contact form",
    "",
    `Name: ${p.name}`,
    `Email: ${p.email}`,
    `Phone: ${p.phone}`,
    `Group size & date: ${p.details || "—"}`,
    "",
    "Message:",
    p.message,
    "",
    `Reply directly to this email to respond to ${p.name}.`,
    footer,
  ].join("\n");
}

export type SendResult =
  | { ok: true; id?: string; mode: EmailMode }
  | { ok: false; error: string; mode: EmailMode };

// Required deliverability headers applied to every email this site sends.
// Per Resend's deliverability guide:
//   - List-Unsubscribe / List-Unsubscribe-Post: required by Gmail and Yahoo
//     bulk-sender rules; signals a properly managed list even for low-volume
//     transactional mail.
//   - Auto-Submitted: RFC 3834. Tells receiving systems this is generated by
//     a process, not a person — suppresses auto-replies and out-of-office
//     loops.
//   - X-Entity-Ref-ID: Resend's recommended dedup key (also helps if the
//     receiving inbox does its own dedup).
function deliverabilityHeaders(opts: {
  unsubscribeMailto: string;
  unsubscribeUrl: string;
  refId: string;
}): Record<string, string> {
  return {
    "List-Unsubscribe": `<mailto:${opts.unsubscribeMailto}?subject=unsubscribe>, <${opts.unsubscribeUrl}>`,
    "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
    "Auto-Submitted": "auto-generated",
    "X-Entity-Ref-ID": opts.refId,
  };
}

export async function sendContactEmail(
  payload: ContactPayload,
): Promise<SendResult> {
  const mode = getEmailMode();

  if (mode === "log_only") {
    return { ok: true, mode };
  }

  const { apiKey, from } = getSenderConfig(mode);
  if (!apiKey) {
    return {
      ok: false,
      mode,
      error: `Missing API key for mode "${mode}". Set ${mode === "fallback_sender" ? "RESEND_API_KEY_FALLBACK" : "RESEND_API_KEY"}.`,
    };
  }

  const to = process.env.CONTACT_EMAIL_TO || "bookings@destinbonfirecompany.com";
  const replyTo = process.env.CONTACT_EMAIL_REPLY_TO || payload.email;
  const refId = randomUUID();
  const unsubscribeMailto =
    process.env.CONTACT_EMAIL_UNSUBSCRIBE_MAILTO || to;
  const unsubscribeUrl =
    process.env.CONTACT_EMAIL_UNSUBSCRIBE_URL ||
    `${SITE.domain}/refund-policy#contact`;

  const htmlBody = buildHtmlBody(
    payload,
    htmlFooter({ unsubscribeUrl }),
  );
  const textBody = buildTextBody(
    payload,
    textFooter({ unsubscribeUrl }),
  );

  try {
    const resend = new Resend(apiKey);
    const { data, error } = await resend.emails.send({
      from,
      to: [to],
      replyTo,
      subject: `New booking inquiry from ${payload.name}`,
      html: htmlBody,
      text: textBody,
      headers: deliverabilityHeaders({
        unsubscribeMailto,
        unsubscribeUrl,
        refId,
      }),
    });
    if (error) {
      return { ok: false, mode, error: error.message || String(error) };
    }
    return { ok: true, mode, id: data?.id };
  } catch (err) {
    return {
      ok: false,
      mode,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}
